### ISSUE TITLE
若干修正建议

### ISSUE THREAD

**Issue by stanleyguo0207** [forthespada/InterviewGuide#2]
- markdown 语法解析

  章节 1、在main执行之前和之后执行的代码可能是什么？

  __attribute__((constructor)) => `__attribute__((constructor))`

  __attribute__((destructor)) => `__attribute__((destructor))`

---

- 内存对齐补充

  章节 2、结构体内存对齐问题？

  - c++11以后引入两个关键字[alignas](https://zh.cppreference.com/w/cpp/language/alignas)与[alignof](https://zh.cppreference.com/w/cpp/language/alignof)。`alignof`可以计算出类型的对齐方式。`alignas`可以指定结构体的对齐方式。但是`alignas`在某些情况下是不能使用的，具体见下面的例子:

  ```c++
  // alignas 生效的情况

  struct Info {
    uint8_t a;
    uint16_t b;
    uint8_t c;
  };

  std::cout << sizeof(Info) << std::endl;   // 6  2 + 2 + 2
  std::cout << alignof(Info) << std::endl;  // 2

  struct alignas(4) Info2 {
    uint8_t a;
    uint16_t b;
    uint8_t c;
  };

  std::cout << sizeof(Info2) << std::endl;   // 8  4 + 4
  std::cout << alignof(Info2) << std::endl;  // 4
  ```
  `alignas`将内存对齐调整为4个字节。所以`sizeof(Info2)`的值变为了8。

  ```c++
  // alignas 失效的情况

  struct Info {
    uint8_t a;
    uint32_t b;
    uint8_t c;
  };

  std::cout << sizeof(Info) << std::endl;   // 12  4 + 4 + 4
  std::cout << alignof(Info) << std::endl;  // 4

  struct alignas(2) Info2 {
    uint8_t a;
    uint32_t b;
    uint8_t c;
  };

  std::cout << sizeof(Info2) << std::endl;   // 12  4 + 4 + 4
  std::cout << alignof(Info2) << std::endl;  // 4
  ```
  若`alignas`小于自然对齐的最小单位，则被忽略。

- 如果想使用单字节对齐的方式，使用`alignas`是无效的。应该使用`#pragma pack(push,1)`或者使用`__attribute__((packed))`。

  ```c++
  #if defined(__GNUC__) || defined(__GNUG__)
    #define ONEBYTE_ALIGN __attribute__((packed))
  #elif defined(_MSC_VER)
    #define ONEBYTE_ALIGN
    #pragma pack(push,1)
  #endif

  struct Info {
    uint8_t a;
    uint32_t b;
    uint8_t c;
  } ONEBYTE_ALIGN;

  #if defined(__GNUC__) || defined(__GNUG__)
    #undef ONEBYTE_ALIGN
  #elif defined(_MSC_VER)
    #pragma pack(pop)
    #undef ONEBYTE_ALIGN
  #endif

  std::cout << sizeof(Info) << std::endl;   // 6 1 + 4 + 1
  std::cout << alignof(Info) << std::endl;  // 6
  ```

- 确定结构体中每个元素大小可以通过下面这种方法:

  ```cpp
  #if defined(__GNUC__) || defined(__GNUG__)
    #define ONEBYTE_ALIGN __attribute__((packed))
  #elif defined(_MSC_VER)
    #define ONEBYTE_ALIGN
    #pragma pack(push,1)
  #endif

  /**
  * 
  * 0 1   3     6   8 9            15
  * +-+---+-----+---+-+-------------+
  * | |   |     |   | |             |
  * |a| b |  c  | d |e|     pad     |
  * | |   |     |   | |             |
  * +-+---+-----+---+-+-------------+
  *
  */
  struct Info {
    uint16_t a : 1;
    uint16_t b : 2;
    uint16_t c : 3;
    uint16_t d : 2;
    uint16_t e : 1;
    uint16_t pad : 7;
  } ONEBYTE_ALIGN;

  #if defined(__GNUC__) || defined(__GNUG__)
    #undef ONEBYTE_ALIGN
  #elif defined(_MSC_VER)
    #pragma pack(pop)
    #undef ONEBYTE_ALIGN
  #endif

  std::cout << sizeof(Info) << std::endl;   // 2
  std::cout << alignof(Info) << std::endl;  // 1
  ```
  这种处理方式是`alignas`处理不了的。

---

- 虚函数问题

  33、为什么析构函数一般写成虚函数

  存在一种特例，在`CRTP`模板中，不应该将析构函数声明为虚函数，理论上所有的父类函数都不应
  该声明为虚函数，因为这种继承方式，不需要虚函数表。

  34、构造函数能否声明为虚函数或者纯虚函数，析构函数呢？

  构造函数不能声明为虚函数的原因之一如下:

  - 虚函数对应一个vtable(虚函数表)，类中存储一个vptr指向这个vtable。如果构造函数是虚函数，就需要通过vtable调用，可是对象没有初始化就没有vptr，无法找到vtable，所以构造函数不能是虚函数。

---

- 拼写错误

  45、什么情况下会调用拷贝构造函数

  `总结就是：即使发生NRA优化的情况下，` =》 `总结就是：即使发生NRV优化的情况下，`

**Comment by forthespada** [comment]
感谢您宝贵的修正意见，非常感谢！！！！

**Comment by stanleyguo0207** [comment]
总结的挺好的，有不少重复的，还没看完，正在看。

**Comment by forthespada** [comment]
这个仓库就我一个人在搞，里面有些问题和知识点我知道重复了，只能说是慢慢迭代吧，不断删减之类的。
哈哈 谢谢你的宝贵意见啊

**Comment by shiqi-lu** [comment]
给阿秀的细致整理点个赞，我也加一条小建议：能否对C++中200+个知识点做一下分类，现在是有点乱序的，其实可以简单划分一下，例如基础、类和对象、STL等等，，，稍微排序一下可读性更高，其它的版块也是同理

**Comment by forthespada** [comment]
谢谢建议，这个建议很好，我打算重新整理一下 哈哈，感谢啦

**Comment by EricPengShuai** [comment]
@forthespada 为啥把之前分开整理的知识储备全部合在一起啊，感觉分开在github挺好的，方便在线看

**Comment by forthespada** [comment]
@EricPengShuai 准备推出在线文档版了，这几天正在弄，到时候看起来会好很多。

**Comment by fu-yao** [comment]
#if defined(__GNUC__) || defined(__GNUG__)
  #define ONEBYTE_ALIGN __attribute__((packed))
#elif defined(_MSC_VER)
  #define ONEBYTE_ALIGN
  #pragma pack(push,1)
#endif

struct Info {
  uint8_t a;
  uint32_t b;
  uint8_t c;
} ONEBYTE_ALIGN;

#if defined(__GNUC__) || defined(__GNUG__)
  #undef ONEBYTE_ALIGN
#elif defined(_MSC_VER)
  #pragma pack(pop)
  #undef ONEBYTE_ALIGN
#endif

std::cout << sizeof(Info) << std::endl;   // 6 1 + 4 + 1
std::cout << alignof(Info) << std::endl;  // 6

//错误订正，最后一个cout应该使1吧。
