### ISSUE TITLE
C++基础：”37、public、protected 和 private 访问和继承权限/public/protected/private的区别？“（补充理解）

### ISSUE THREAD

**Issue by onetaste061** [forthespada/InterviewGuide#35]
一、访问权限

访问权限   |  外部  | 派生类  |  内部  |
-|-|-|-|
public    |   ✔   |   ✔    |   ✔    |
protected |   ❌  |   ✔    |   ✔    |
private   |  ❌   |   ❌   |   ✔    |

public、protected、private 的访问权限范围关系：

public > protected > private

二、继承权限

1. 派生类继承自基类的成员权限有四种状态：public、protected、private、不可见

2. 派生类对基类成员的访问权限取决于两点：一、继承方式；二、基类成员在基类中的访问权限

3. 派生类对基类成员的访问权限是取以上两点中的更小的访问范围（除了 private 的继承方式遇到 private 成员是不可见外）。例如：

  - public 继承  + private 成员     =>  private
  
  - private 继承 + protected 成员 =>  private 
  
  - private 继承 + private 成员    =>  不可见

**Comment by forthespada** [comment]
谢谢总结，已添加！

**Comment by vaeFmn** [comment]
你好，请问你这个是否有误呢，我觉得应该是public 继承 + private 成员 => 不可见，自己也测试验证了一下。

**Comment by yuyuyuj1e** [comment]
基类 private 所有成员对于子类来说都是不可见的，无论是什么方式继承
