### ISSUE TITLE
适用于毕业三年内的互联网社招同学？

### ISSUE THREAD

**Issue by onlyet** [forthespada/InterviewGuide#47]
您好，毕业超过三年不适合看这个吗？

**Comment by GHower** [comment]
正常超过三年都是问实际经验的了，问经历的了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月26日(星期二) 上午10:36
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [forthespada/InterviewGuide] 适用于毕业三年内的互联网社招同学？ (Issue #47)




 
您好，毕业超过三年不适合看这个吗？

**Comment by onlyet** [comment]
@GHower 我问的是大佬，没问你

**Comment by forthespada** [comment]
首先，emm，我不是什么大佬，只是个小菜鸡，这些笔记也只是我自己总结出来的。。。
其次，上面那位同学说的是对的，一般超过3年基本会问工作中的实际经验和做过的项目了，死板知识考的不多了，五年之上更是如此哈。
不过如果你感觉自己工作比较simple，那就多看看这些知识点吧

**Comment by onlyet** [comment]
@forthespada 好的，谢谢回复，我连菜鸡都算不上。

**Comment by GHower** [comment]
秀哥要不在前面的章节，加上这些常见问题吧，都见人问好多次了😂



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月26日(星期二) 中午12:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [forthespada/InterviewGuide] 适用于毕业三年内的互联网社招同学？ (Issue #47)




 
首先，emm，我不是什么大佬，只是个小菜鸡，这些笔记也只是我自己总结出来的。。。
 其次，上面那位同学说的是对的，一般超过3年基本会问工作中的实际经验和做过的项目了，死板知识考的不多了，五年之上更是如此哈。
 不过如果你感觉自己工作比较simple，那就多看看这些知识点吧
