### ISSUE TITLE
 InterviewGuide勘误

### ISSUE THREAD

**Issue by GitHubQAQ** [forthespada/InterviewGuide#50]
在C++基础知识40部分（什么情况下会调用拷贝构造函数）：
![image](https://user-images.githubusercontent.com/31883473/169481752-ecf490c1-e7d1-40c0-bcc9-3a8750fbc609.png)

此处的代码不够规范，含义模糊
```cpp
A a1, a2, a3, a4;
A a2 = a1;
```
理由如下：
如果是上述代码，在Windows+vs2017(默认MSVC)下测试，“错误 C2374 “a2”: 重定义；多次初始化”
建议修改为：
```cpp
A a1;
A a2 = a1;
```

**Comment by forthespada** [comment]
ths!
